=== mkantem/XML/entreprise/entreprise.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="entreprise">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="agent" maxOccurs="unbounded" type="TYPE_AGENT"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:complexType name="TYPE_AGENT">
        <xsd:sequence>
            <xsd:element name="matricule" type="xsd:string"></xsd:element>
            <xsd:element name="prenom" type="xsd:string"></xsd:element>
            <xsd:element name="nom" type="xsd:string"></xsd:element>
            <xsd:element name="datePS" type="xsd:date"></xsd:element>
            <xsd:element name="postes" maxOccurs="unbounded" type="TYPE_POSTE"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="type">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Femme"></xsd:enumeration>
                    <xsd:enumeration value="Homme"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="TYPE_POSTE">
        <xsd:sequence>
            <xsd:element name="poste" maxOccurs="unbounded" type="T_P"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="T_P">
        <xsd:attribute name="code" type="xsd:int" use="required"></xsd:attribute>
        <xsd:attribute name="titre" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="salaire" type="xsd:double" use="required"></xsd:attribute>
        <xsd:attribute name="enActivite">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Oui"></xsd:enumeration>
                    <xsd:enumeration value="Non"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== mkantem/XML/entreprise/entreprisexsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<entreprise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/Z:/Teaching/2022%20-%202023/XML%20et%20Web%20Services/workspace/entreprise/entreprise.xsd">
    
    <agent type="Femme">
        <matricule>A0121</matricule>
        <prenom>Mariam</prenom>
        <nom>Diaby</nom>
        <datePS>2021-12-02</datePS>
        <postes>
            <poste code="02" titre="Admin reseau" salaire="450000" enActivite="Non"/>
            <poste code="05" titre="Chef DSI" salaire="1500000" enActivite="Oui"/>
        </postes>
    </agent>
    
    <agent type="Homme">
        <matricule>2BV56</matricule>
        <prenom>Ibrahim</prenom>
        <nom>Toure</nom>
        <datePS>2014-05-14</datePS>
        <postes>
            <poste code="14" titre="Support IT" salaire="200000" enActivite="Oui"/>
        </postes>
    </agent>
    
</entreprise>
